sudo: required

language: generic 

services:
  - docker

before_install:
  - docker build -t ukran1um/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ukran1um/docker-react npm run test